---
title: "Predicting Stock Index Realised Volatility using Bayesian VARs"
author: "Nathan Huynh"

format:
  html:
    toc: true
    toc-location: left

execute:
  echo: false

knitr:
  opts_knit:
    root.dir: "C:\\Users\\Nathan\\Documents\\GitHub\\mcxs_report"

bibliography: references.bib
---

> **Abstract:** This research report explores whether VARs and Bayesian VARs are able to predict realised volatility in equity index markets.
>
> **Keywords.** BVARs, Realised Volatility, Stock Indices, SP500

# Research Proposal

## Objective and Motivation

This paper seeks to examine the effectiveness of Bayesian VARs as a method for forecasting realised volatility (**RV**) in equity markets. It will explore whether various Bayesian estimation techniques applied to vector autoregression can accurately predict RV. The accurate prediction of market volatility has many applications in Finance, including the pricing of derivatives and the estimation of risk measures such as Value at Risk.

## Data

The models will be applied to daily data on realised variances occurring on a group of global stock indices. Stock indices serve as gauges of overall equity market performance and are generally categorised by country. For this analysis we will focus on 10 major global indices, the SPX, DJI, FTSE, GDAXI, FCHI, STOXX50E, N225, AORD, HSI and the STI.

Realised variance is a measure of historical volatility occuring in financial time series constructed from intraday high frequency return data.

Realised variance is defined as the sum of squared returns over specific period:
```{=tex}
\begin{align}
Realised\,Variance = \sum r^2_t
\end{align}
```
Where $p_t$ denotes the price of an asset at time t and $r_t$ is defined as the log return over a predetermined interval, for example 5 minutes:
```{=tex}
\begin{align}
r_t = log(p_t / p_{t-1})
\end{align}
```
Realised volatility **RV** is then computed as the square root of the realised variance.
```{=tex}
\begin{align}
RV = \sqrt{\sum r^2_t}
\end{align}
```

The RV data is sourced from the [Oxford Man Realised Library](https://oxford-man.ox.ac.uk/) which provides a number of precalculated volatility metrics, including RV on stock indices spanning multiple years. For this analysis we will utilise the 5 minute RV measure provided in the dataset for each of our 10 indices.

##### Figure 1. Time series plots of original values {style="text-align: center;"}
```{R loading in data}

#Sourcing RV data from the Oxford Man Realized Library

temp <- tempfile()
download.file("https://github.com/onnokleen/mfGARCH/raw/v0.1.9/data-raw/OxfordManRealizedVolatilityIndices.zip",temp)
data <- read.csv(unz(temp, "oxfordmanrealizedvolatilityindices.csv"))
unlink(temp)

#Putting the RV data in a dataframe

SPX = na.omit(xts::xts(data[data$Symbol=='.SPX', 'rv5'],as.Date(data[data$Symbol=='.SPX', 'X'])))
FTSE = na.omit(xts::xts(data[data$Symbol=='.FTSE', 'rv5'],as.Date(data[data$Symbol=='.FTSE', 'X'])))
DAX = na.omit(xts::xts(data[data$Symbol=='.GDAXI', 'rv5'],as.Date(data[data$Symbol=='.GDAXI', 'X'])))
NIKKEI = na.omit(xts::xts(data[data$Symbol=='.N225', 'rv5'],as.Date(data[data$Symbol=='.N225', 'X'])))

df <- as.data.frame(
  merge(SPX, 
        FTSE, 
        DAX, 
        NIKKEI))

colnames(df) <- c("S&P Daily RV","FTSE Daily RV","DAX Daily RV","Nikkei Daily RV")
dates <- as.Date(rownames(df),format = "%Y-%m-%d")
titles <- c("S&P Daily RV","FTSE Daily RV","DAX Daily RV","Nikkei Daily RV")

#Plotting the original values of 4 indices 

par(mfrow=c(2,2), mar=c(3,3,2,2))
for (i in 1:ncol(df)){
  plot(dates, y = df[,i], type = "l", 
       main = titles[i], ylab = "RV", xlab = "Date",
       col = 'blue',
       ylim = c(min(na.omit(df[,i])),max(na.omit(df[,i]))))
}
```
# 

From a visual inspection of the examples above, we can see that realised volatility appears highly non-stationary. There are clear spikes in RV over certain periods in time. These periods of high volatility appear to persist for some time before subsiding, which provides evidence in favour of an autoregressive model specification.

Furthermore, spikes in RV appear to happen around the same times across markets. This provides our main motivation for modelling RV via a VAR specification whereby we can seek to capture the dynamic interrelationships between global equity markets.

For ease of modelling and in order to bring the data closer to normality we will work with the log transformed variable $log(rv_t)$.

##### Figure 2. Time series plots of log transformed values {style="text-align: center;"}
```{r}
#Storing log transformed variables in a dataframe

df.log <- as.data.frame(
  merge(log(SPX), 
        log(FTSE), 
        log(DAX), 
        log(NIKKEI)))
colnames(df.log) <- c("S&P log RV","FTSE log RV","DAX Daily RV","Nikkei log RV")
dates <- as.Date(rownames(df.log),format = "%Y-%m-%d")
new_titles <- c("S&P log RV","FTSE log RV","DAX log RV","Nikkei log RV")

#Plotting the log transformed values of 4 indices

par(mfrow=c(2,2), mar=c(3,3,2,2))
for (i in 1:ncol(df.log)){
  plot(dates, y = df.log[,i], type = "l", ylab = "RV", xlab = "Date",
       main = new_titles[i],
       col = 'blue'
       )
}

```


## Model

The model will follow the standard $VAR(p)$ setup as follows:

```{=tex}
\begin{align}
rv_t &= \mu_0 + A_1 rv_{t-1} + \dots + A_p rv_{t-p} + \epsilon_t\\
\epsilon_t | RV_{t-1} &\sim iidN_N(0_N, \Sigma)
\end{align}
```

Where $rv_t$ is a vector of log transformed realised variances for our $N=10$ stock indices on day $t$. The $A_i$ matrices are $N\times N$ matrices of the autoregressive slope parameters.

The error term vector $\epsilon_t$ given the data up to $t-1$ is assumed to be iid multivariate normally distributed of dimension $N=10$, with mean $0_N$ and covariance matrix $\Sigma$.

Bayesian estimation techniques will be then utilised in conjunction with a number of suitably chosen prior specifications in order to estimate competing models and compute 1 day ahead RV forecasts across all indices. The predictions will be made out of sample and the accuracy of the forecasts will then be assessed according to their root mean squared errors **RMSE**, given by:

```{=tex}
\begin{align}
RMSE = \sqrt{\sum(\hat{rv_i} - rv_i )^2/n}
\end{align}
```

Assessment of prediction accuracy via the RMSEs will facilitate comparison of various different model specifications, such as the incorporation of different prior distributions and differing assumptions about the parameters of those distributions.

The significance of being able to reliably forecast market volatility is primarily seen in the context of financial asset pricing. Volatility of the underlying asset is one of the crucial inputs required in options pricing. With reliable forecasts of stock index volatility one can assess the degree to which options quoted in the market are under or over estimating volatility relative to what is indicated by the historical realised dynamics.

